# Copyright 2025 Matt Borland
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/doc"
    schedule:
      interval: "weekly"
